image: java:openjdk-8-jdk

services:
  - postgres:latest

variables:
  POSTGRES_DB: giddy
  POSTGRES_HOST: $GIDDY_POSTGRES_DB_HOST
  POSTGRES_USER: $GIDDY_POSTGRES_DB_USERNAME
  POSTGRES_PASSWORD: $GIDDY_POSTGRES_DB_PASSWORD

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew build buildDocker

test:
  stage: test
  script:
    - ./gradlew check

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
  only:
  - master

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
  when: manual
  only:
  - master
