image: java:openjdk-8-jdk

services:
  - postgres:latest

variables:
  POSTGRES_DB: giddy
  POSTGRES_USER: ""
  POSTGRES_PASSWORD: ""

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew check