image: frolvlad/alpine-oraclejdk8:slim

services:
  - postgres:latest

variables:
  POSTGRES_DB: giddy
  POSTGRES_HOST: $GIDDY_POSTGRES_DB_HOST
  POSTGRES_USER: $GIDDY_POSTGRES_DB_USERNAME
  POSTGRES_PASSWORD: $GIDDY_POSTGRES_DB_PASSWORD

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew build buildDocker

test:
  stage: test
  script:
    - ./gradlew check
