image: frekele/gradle

services:
  - postgres:latest

variables:
  POSTGRES_DB: giddy
  POSTGRES_USER: ""
  POSTGRES_PASSWORD: ""

cache:
  paths:
    - .gradle/

build:
  script: "gradle clean build"