import com.graphhopper.GraphHopper;
import com.graphhopper.routing.util.*;

import java.util.Set;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rik' at '8/16/16 7:06 PM' with Gradle 2.14
 *
 * @author rik, @date 8/16/16 7:06 PM
 */
public class GiddyHopper extends GraphHopper {

    Set<Integer> forbiddenEdges;
    public void determineForbiddenEdges() {
    //    forbiddenEdges = ...
    }

    @Override
    public Weighting createWeighting(HintsMap weightingMap, FlagEncoder encoder )
    {
        String weighting = weightingMap.getWeighting().toLowerCase();

        if ("BLOCKING".equalsIgnoreCase(weighting))
        {
            SafeEdgesWeighting w = new SafeEdgesWeighting(encoder);
            w.addEdges(forbiddenEdges);
            return w;
        } else
        {
            return super.createWeighting(weightingMap, encoder);
        }

    }
}
