import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'rik' at '8/16/16 7:06 PM' with Gradle 2.14
 *
 * @author rik, @date 8/16/16 7:06 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        GiddyHopper classUnderTest = new GiddyHopper();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
